<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="2" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-06T17:00:53 IST" name="Suite" finished-at="2025-07-06T17:12:32 IST" duration-ms="699207">
    <groups>
      <group name="Master">
        <method signature="TC01_AccountLoginTest.Verify_Account_Registartion()[pri:0, instance:testCases.TC01_AccountLoginTest@732f29af]" name="Verify_Account_Registartion" class="testCases.TC01_AccountLoginTest"/>
        <method signature="TC02_AccountLoginUsingDataProvider.Verify_LoginAccountUsingDataProvider(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_AccountLoginUsingDataProvider@158a3b2e]" name="Verify_LoginAccountUsingDataProvider" class="testCases.TC02_AccountLoginUsingDataProvider"/>
      </group> <!-- Master -->
      <group name="sanity">
        <method signature="TC01_AccountLoginTest.Verify_Account_Registartion()[pri:0, instance:testCases.TC01_AccountLoginTest@732f29af]" name="Verify_Account_Registartion" class="testCases.TC01_AccountLoginTest"/>
      </group> <!-- sanity -->
      <group name="dataDriven">
        <method signature="TC02_AccountLoginUsingDataProvider.Verify_LoginAccountUsingDataProvider(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_AccountLoginUsingDataProvider@158a3b2e]" name="Verify_LoginAccountUsingDataProvider" class="testCases.TC02_AccountLoginUsingDataProvider"/>
      </group> <!-- dataDriven -->
    </groups>
    <test started-at="2025-07-06T17:00:53 IST" name="Test" finished-at="2025-07-06T17:12:32 IST" duration-ms="699207">
      <class name="testCases.TC01_AccountLoginTest">
        <test-method is-config="true" signature="setup(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC01_AccountLoginTest@732f29af]" started-at="2025-07-06T17:00:53 IST" name="setup" finished-at="2025-07-06T17:00:59 IST" duration-ms="6461" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Verify_Account_Registartion()[pri:0, instance:testCases.TC01_AccountLoginTest@732f29af]" started-at="2025-07-06T17:00:59 IST" name="Verify_Account_Registartion" finished-at="2025-07-06T17:01:10 IST" duration-ms="10340" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Account_Registartion -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.TC01_AccountLoginTest@732f29af]" started-at="2025-07-06T17:01:10 IST" name="tearDown" finished-at="2025-07-06T17:01:11 IST" duration-ms="1034" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TC01_AccountLoginTest -->
      <class name="testCases.TC02_AccountLoginUsingDataProvider">
        <test-method is-config="true" signature="setup(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_AccountLoginUsingDataProvider@158a3b2e]" started-at="2025-07-06T17:01:11 IST" name="setup" finished-at="2025-07-06T17:01:15 IST" duration-ms="3834" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Verify_LoginAccountUsingDataProvider(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_AccountLoginUsingDataProvider@158a3b2e]" started-at="2025-07-06T17:01:16 IST" name="Verify_LoginAccountUsingDataProvider" data-provider="LoginData" finished-at="2025-07-06T17:04:24 IST" duration-ms="187371" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[abc@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[349988]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[invalid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_LoginAccountUsingDataProvider -->
        <test-method signature="Verify_LoginAccountUsingDataProvider(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_AccountLoginUsingDataProvider@158a3b2e]" started-at="2025-07-06T17:04:24 IST" name="Verify_LoginAccountUsingDataProvider" data-provider="LoginData" finished-at="2025-07-06T17:07:24 IST" duration-ms="180016" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[9090984098]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Password@8]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[invalid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testCases.TC02_AccountLoginUsingDataProvider.Verify_LoginAccountUsingDataProvider(TC02_AccountLoginUsingDataProvider.java:84)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_LoginAccountUsingDataProvider -->
        <test-method signature="Verify_LoginAccountUsingDataProvider(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_AccountLoginUsingDataProvider@158a3b2e]" started-at="2025-07-06T17:10:24 IST" name="Verify_LoginAccountUsingDataProvider" data-provider="LoginData" finished-at="2025-07-06T17:12:32 IST" duration-ms="127971" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[xyz@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[565656]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[invalid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testCases.TC02_AccountLoginUsingDataProvider.Verify_LoginAccountUsingDataProvider(TC02_AccountLoginUsingDataProvider.java:84)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_LoginAccountUsingDataProvider -->
        <test-method signature="Verify_LoginAccountUsingDataProvider(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_AccountLoginUsingDataProvider@158a3b2e]" started-at="2025-07-06T17:12:32 IST" name="Verify_LoginAccountUsingDataProvider" data-provider="LoginData" finished-at="2025-07-06T17:12:32 IST" duration-ms="11" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[8308984098]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Password@8]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Valid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testCases.TC02_AccountLoginUsingDataProvider.Verify_LoginAccountUsingDataProvider(TC02_AccountLoginUsingDataProvider.java:84)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_LoginAccountUsingDataProvider -->
        <test-method signature="Verify_LoginAccountUsingDataProvider(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_AccountLoginUsingDataProvider@158a3b2e]" started-at="2025-07-06T17:12:32 IST" name="Verify_LoginAccountUsingDataProvider" data-provider="LoginData" finished-at="2025-07-06T17:12:32 IST" duration-ms="13" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testCases.TC02_AccountLoginUsingDataProvider.Verify_LoginAccountUsingDataProvider(TC02_AccountLoginUsingDataProvider.java:84)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_LoginAccountUsingDataProvider -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.TC02_AccountLoginUsingDataProvider@158a3b2e]" started-at="2025-07-06T17:12:32 IST" name="tearDown" finished-at="2025-07-06T17:12:32 IST" duration-ms="33" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TC02_AccountLoginUsingDataProvider -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
